#!/bin/bash

exec 1>>install.log

apt-get install -y apt-transport-https
apt-get install -y software-properties-common wget

wget -qO- https://repos.influxdata.com/influxdb.key | apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | tee /etc/apt/sources.list.d/influxdb.list

wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
echo "deb https://packages.grafana.com/enterprise/deb stable main" | tee -a /etc/apt/sources.list.d/grafana.list 

apt -y update
apt -y install grafana-enterprise
apt -y install influxdb
apt -y install nginx


wget https://raw.githubusercontent.com/mtsprout/statscollector/master/files/default -O /etc/nginx/sites-available/default

systemctl enable influxdb
systemctl enable grafana-server
systemctl enable nginx

systemctl daemon-reload

systemctl restart influxdb
systemctl restart grafana-server
systemctl restart nginx

echo "CREATE DATABASE perf" | influx || die "Error creating influx database."
