#!/bin/bash

yum -y install wget epel-release
yum -y install nginx

wget https://raw.githubusercontent.com/mtsprout/statscollector/master/files/grafana.repo -o /etc/yum.repos.d/grafana.repo
wget https://raw.githubusercontent.com/mtsprout/statscollector/master/files/influxdb.repo -o /etc/yum.repos.d/influxdb.repo
wget https://raw.githubusercontent.com/mtsprout/statscollector/master/files/grafana.conf -o /etc/nginx/conf.d/grafana.conf

yum -y install grafana
yum -y install influxdb

systemctl enable influxdb
systemctl enable grafana
systemctl enable nginx

systemctl start influxdb
systemctl start grafana
systemctl start nginx
